In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import xlsxwriter
import pandas as pd
import os
import xlrd
import numpy as np
from pandas import DataFrame

In [2]:
pwd

'/Users/antonshirokov'

In [3]:
colnames = ['target']
colnames1 = ['days_in_business', 'yelp_review_count', 'yelp_rating', 'google_rating']
#df = pd.read_csv("/Users/antonshirokov/Desktop/100_businesses/Targets.csv", names = colnames)
#df = pd.read_csv("/Users/antonshirokov/Desktop/100_businesses/Targets_5_class.csv", names = colnames)
df = pd.read_csv("/Users/antonshirokov/Desktop/100_businesses/Targets_3_class.csv", names = colnames)
df1 = pd.read_csv("/Users/antonshirokov/Desktop/100_Businesses/Features_Standardized.csv", names = colnames1)
#df1 = pd.read_csv("/Users/antonshirokov/Desktop/100_businesses/Features_Min_Max_Normalized.csv", names = colnames1)
c = np.array(df)
#print(c)

In [4]:
y = np.array(df.target.tolist())
X = np.array(df1)

In [5]:
print(y)

[0 0 0 1 0 2 2 1 1 1 2 2 2 2 2 2 1 1 0 2 1 1 2 1 0 0 2 1 2 1 1 1 2 2 2 1 1
 1 2 1 2 1 1 2 1 2 2 2 2 0 0 0 0 2 0 1 0 2 0 0 0 1 1 1 0 1 0 1 1 0 1 2 2 1
 0 1 2 2 2 2 2 2 2 2 0 2 0 0 0 0]


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/Users/antonshirokov/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/antonshirokov/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
y_pred = logreg.predict(X_test)
print(y_pred)
print(y_test)
print(X_test)

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

[0 1 1 1 1 1 2 2 2 2 1 2 2 0 1 2 1 0]
[0 2 2 1 0 1 2 2 2 0 1 2 2 1 1 1 0 0]
[[ 2.27862627 -0.47758027  1.02111841 -2.72602921]
 [-0.65205862 -0.1880442  -0.02917481  0.33727263]
 [-0.05068611 -0.27926789  0.4959718  -0.15007085]
 [-0.65982012 -0.4299853  -0.55432142  0.12841114]
 [-0.53391135 -0.47361402  1.02111841 -0.08045035]
 [-0.11450289 -0.39825532 -0.55432142  0.7549956 ]
 [ 0.09304537  1.60469967 -0.02917481  0.40689312]
 [-0.52011312  2.24723177 -0.02917481  0.40689312]
 [ 2.24873012  1.84664077  0.4959718   0.54613411]
 [-1.79616121 -0.46964778  1.02111841  0.7549956 ]
 [ 0.11747972 -0.46964778 -1.60461465  0.54613411]
 [ 0.39286924  0.68453025  0.4959718   0.54613411]
 [-0.66585685 -0.32686286  1.02111841  0.7549956 ]
 [ 1.11900068 -0.41015406 -0.55432142 -1.12475779]
 [-0.53822329 -0.06509053 -0.55432142 -0.08045035]
 [ 0.24137626 -0.46568153  1.02111841  0.7549956 ]
 [-0.61152635 -0.46964778 -0.02917481  0.19803163]
 [-0.47871846 -0.45774903 -2.65490787 -0.77665531]]
Accur